Replace apache http client with airlift
trinodb/trino-gateway pull request #142
Opened 2024-01-03 14:13 UTC by ebyhr

2024-01-09 03:32 UTC, mosabua commented on gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
> +    private static final int HTTP_OK_CODE = 200;
Remove

2024-01-09 03:35 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
> +    private static final int HTTP_OK_CODE = 200;
This constant is used in L155.

2024-01-09 03:50 UTC, mosabua requested changes

2024-01-09 03:50 UTC, mosabua commented on gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
>                      return res.body().string();
use 

HttpStatus.OK_200

from Jetty instead

2024-01-09 03:50 UTC, mosabua commented on gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
> +                case HTTP_UNAUTHORIZED_CODE:
use HttpStatus.UNAUTHORIZED_401

2024-01-09 03:50 UTC, mosabua commented on gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyHandler.java
> +        String contentEncoding = response.getHeader("Content-Encoding");
Use HttpHeader.CONTENT_ENCODING from jetty

2024-01-09 04:32 UTC, mosabua commented on gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
> +    private static final int HTTP_OK_CODE = 200;
See below... both are not needed.

2024-01-11 01:43 UTC, mosabua approved these changes
Looks good to me now. Thank you @ebyhr

2024-01-11 02:04 UTC, merged