Add dockerized cluster stats monitor test
trinodb/trino-gateway pull request #144
Opened 2024-01-04 01:09 UTC by ebyhr

Also, remove unhelpful mock based test.

2024-01-05 17:30 UTC, mosabua submitted a review, later dismissed

2024-01-05 17:30 UTC, mosabua commented on gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
> +        backendStateConfiguration.setUsername("Trino");
Use a different username to avoid overlap with cluster name

2024-01-05 17:30 UTC, mosabua commented on gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
> +        proxyBackend.setName("Trino");
Use a different name ideally. example_cluster, cluster1 or whatever

2024-01-05 23:20 UTC, ebyhr commented
Addressed comments.

2024-01-09 03:25 UTC, mosabua requested changes
Looks good now.

2024-01-09 03:25 UTC, mosabua approved these changes

2024-01-09 03:26 UTC, merged