added support for oauth2 audience
trinodb/trino-gateway pull request #164
Opened 2024-01-17 17:23 UTC by andythsu

2024-01-17 18:24 UTC, willmostly requested changes
Looks good, one improvement requested to the test setup then I think this is good to go

2024-01-17 18:24 UTC, willmostly commented on gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbTokenUtil.java
> +    private final String idToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0Iiwic3ViIjoidGVzdCIsImF1ZCI6InRlc3QuY29tIn0.YVdTAuEnn-UHsZf5AKA8avaBTLQvdQ3Dd7LeaXKSjlq0atRcmp_IzE8vnJYplYwBs6
Could you use `JWT.create()` to build the token in `setup()`? That would make these tests easier to understand and maintain in the future if new features are desired.

2024-01-24 15:01 UTC, mosabua commented on gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbTokenUtil.java
> +import static org.junit.jupiter.api.Assertions.assertFalse;
Could you refactor this quickly to use assert j ?

2024-01-24 17:48 UTC, mosabua approved these changes
Looks good now.

2024-01-24 17:48 UTC, merged