Clarify the purpose of having resource group in gateway
trinodb/trino-gateway pull request #329
Opened 2024-05-03 00:03 UTC by Chaho12

## Description

People ask what is resource group in gateway every once in a while.
It must be confusing for new users, so I added some sentences to clarify
what resource group in gateway does.
- https://trinodb.slack.com/archives/CG9K9MX1V/p1710174886868119
- https://trinodb.slack.com/archives/CG9K9MX1V/p1714685877520219

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
* 
```

2024-05-03 16:28 UTC, mosabua requested changes
Have a look at my suggestions .. does that make sense? 

Maybe we add some more info from https://trinodb.slack.com/archives/CG9K9MX1V/p1714685877520219

2024-05-03 16:28 UTC, mosabua commented on docs/resource-groups-api.md
> +Resource Groups facilitates the saving and management of the resource group
```suggestion
Resource groups facilitate the configuration of the Trino resource group
```

2024-05-03 16:28 UTC, mosabua commented on docs/resource-groups-api.md
> +required for the [Database Resource Group Manager](https://trino.io/docs/current/admin/resource-groups.html#database-resource-group-manager).
```suggestion
using the [database resource group manager](https://trino.io/docs/current/admin/resource-groups.html#database-resource-group-manager), configured in the Trino Gateway database.
```

2024-05-03 16:28 UTC, mosabua commented on docs/resource-groups-api.md
> +Therefore, in Trino, you would configure the database endpoint for the
Not sure what you want to say here .. I think

```
Configure the resource groups in each Trino backend cluster to use the resource group configuration in the Trino Gateway backend database.
```

2024-05-04 20:23 UTC, alaturqua requested changes
Hi, thanks for the PR. Following would be my suggestion:

Trino Gateway facilitates the management of resource groups across multiple Trino clusters. It allows users to connect their Trino clusters to a centralized resource groups table maintained in the Trino Gateway's backend database. This setup enables management of resource groups either through the [API](https://github.com/trinodb/trino-gateway/blob/main/docs/resource-groups-api.md#resource-groups-api) or the Trino Gateway user interface.

Trino offers both [file-based](https://trino.io/docs/current/admin/resource-groups.html) and [database resource group management](https://trino.io/docs/current/admin/resource-groups.html#database-resource-group-manager). Using Trino Gateway with database management avoids the need for cluster redeployments when updating resource groups, enhancing operational efficiency.

2024-05-30 01:15 UTC, Chaho12 commented
PTAL @mosabua @alaturqua :)

2024-05-30 01:34 UTC, alaturqua commented
@Chaho12 Thanks. It looks good for me.

2024-05-30 01:35 UTC, alaturqua approved these changes

2024-05-30 18:43 UTC, mosabua approved these changes
Looks good now. Thank you.

2024-05-30 18:43 UTC, merged