Add doc for the current routers and steps to add a new one
trinodb/trino-gateway pull request #406
Opened 2024-07-08 19:44 UTC by vishalya

## Description
Add the documentation for the routers and how to add a new router.

## Additional context and related issues
NA

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2024-07-08 21:10 UTC, mosabua requested changes
Please address first comments .. that will make reviewing easier.

2024-07-08 21:10 UTC, mosabua commented on docs/routers.md
> +## Routers
Empty line after each title please .. also start at highest level (#) and dont skip levels

2024-07-08 21:10 UTC, mosabua commented on docs/routers.md
> +Gateway offers two entry-level router options, providing users with a straightforward and easy-to-use starting point for their routing needs.
Please wrap all paragraphs at 80 char width

2024-07-09 00:16 UTC, Chaho12 reviewed
oh you added docs yourself. thx :)
fyi. i was waiting for my [pr](https://github.com/trinodb/trino-gateway/pull/398) regarding changes in passing all headers as MultiValueMap to routing manager to be merged.

2024-07-09 00:16 UTC, Chaho12 commented on docs/routers.md
> +
How about adding a title about what info is available for users to use when making a customized module

2024-07-10 16:31 UTC, mosabua commented on docs/routers.md
> +- Derive a class from `StochasticRoutingManager`,
```suggestion
- Derive a class from `StochasticRoutingManager`
```

2024-07-10 16:31 UTC, mosabua commented on docs/routers.md
> + this is the router which does the actual work
```suggestion
 to create the router that does the actual work
```

2024-07-10 16:31 UTC, mosabua commented on docs/routers.md
> + for the new smarter logic
```suggestion
 and implement the new smarter logic
```

2024-07-10 16:32 UTC, mosabua commented on docs/routers.md
> +- This method gets called on regular intervals defined
```suggestion
- This method is called on regular intervals defined
```

2024-07-10 16:57 UTC, mosabua commented on docs/routers.md
> +are not included in the list. so if you have 3 cluster backends and 1 is
```suggestion
are not included in the list. If you have three cluster backends and one is
```

2024-07-10 16:57 UTC, mosabua commented on docs/routers.md
> +unhealthy then the pamameter `List<ClusterStats> stats` will have only 2 elements.
```suggestion
unhealthy, then the parameter `List<ClusterStats> stats` has only two elements.
```

2024-07-10 16:58 UTC, mosabua commented on docs/routers.md
> +- In order to get the cluster stats use set the parameter
```suggestion
- To get the cluster stats set the parameter
```

2024-07-10 16:58 UTC, mosabua commented on docs/routers.md
> +### Config file reference
```suggestion
### Configuration file reference

```

2024-07-10 16:58 UTC, mosabua commented on docs/routers.md
> +```
```suggestion
```yaml
```

2024-07-19 20:25 UTC, vishalya commented
I have updated the doc as per the comments, please take a look.

2024-07-19 20:53 UTC, merged

2024-07-19 20:54 UTC, mosabua reviewed
Added some final tweaks but this is good to ship. Over time we might need to consolidate some more with the user docs.