Add proxy handler for DELETE method
trinodb/trino-gateway pull request #414
Opened 2024-07-17 16:16 UTC by v2kk

## Description

- Add support for DELETE method on proxyserver

## Additional context and related issues
- Trino client REST API [use DELETE to nextUri terminates a running query](https://trino.io/docs/current/develop/client-protocol.html#http-methods)

## Release notes
( x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2024-07-17 16:28 UTC, v2kk commented
@willmostly yes, in my case, query submitted from airflow result in `trino.exceptions.HttpError: error 405`, the cancel HTTP request does not handled by Trino Gateway

2024-07-17 16:56 UTC, willmostly commented
@v2kk can you add a test, for example https://github.com/trinodb/trino-gateway/compare/main...willmostly:trino-gateway:will/test-delete

2024-07-17 17:06 UTC, willmostly requested changes
The code looks good - please add a test and then this can be merged

2024-07-17 17:49 UTC, willmostly approved these changes
LGTM

2024-07-17 18:33 UTC, mosabua commented
@v2kk did you submit the CLA via email already? We have to wait until it is received and processed before we can merge. cc @martint

2024-07-17 22:39 UTC, mosabua approved these changes
I think this is good. The one thing I think we should consider is adding some javadoc in there that explains why a DELETE request is ever used .. its required for terminating running queries.

2024-07-17 23:58 UTC, oneonestar approved these changes

2024-07-17 23:59 UTC, oneonestar commented
Do we also need to handle other methods like PUT/HEAD?

2024-07-18 00:54 UTC, v2kk commented
@mosabua I just submitted the CLA via email this morning

@oneonestar look like we only need to support 3 methods: GET, POST, DELETE. Trino python client library did it: https://github.com/trinodb/trino-python-client/blob/505989a59e93f6319e8b6be89a16f81034a06404/trino/client.py#L549

2024-07-18 01:01 UTC, Chaho12 approved these changes
LGTM.

2024-07-18 01:02 UTC, Chaho12 commented
same for [go client](https://github.com/trinodb/trino-go-client/blob/master/trino/trino.go), uses GET POST DELETE

2024-07-18 04:07 UTC, mosabua commented
Could you process the CLA of @v2kk please @martint .. we would like to get this merged and cut the 10 release this week if possible.

2024-07-22 18:22 UTC, mosabua commented
@cla-bot check

2024-07-22 18:56 UTC, mosabua commented
@cla-bot check

2024-07-22 18:58 UTC, merged