Update Helm chart version to 10
trinodb/trino-gateway pull request #438
Opened 2024-08-16 12:47 UTC by oneonestar

## Description
Update Helm chart version to 10.
Related to #437.

`version` should follow semantic versioning (X.Y.Z).
I'm thinking about:
```
X follows trino-gateway release
Y for helm chart breaking updates
Z for minor bug fixes
```

wdyt @willmostly 

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

2024-08-19 23:11 UTC, mosabua requested changes

2024-08-19 23:11 UTC, mosabua commented on helm/trino-gateway/Chart.yaml
> +version: "10.0.0"
In our prior syncs we decided to keep Trino Gateway and helm chart versions in sync for now. So at this stage it should be just "10".

2024-08-19 23:11 UTC, mosabua commented on helm/trino-gateway/Chart.yaml
> +version: "10.0.0"
But we can also discuss in the dev sync on Wednesday

2024-08-20 17:30 UTC, mosabua commented
Also note that 10 is a perfectly fine semantic version number as well

2024-08-21 01:55 UTC, oneonestar commented
> Also note that 10 is a perfectly fine semantic version number as well

I don't think so.

https://helm.sh/docs/topics/charts/#charts-and-versioning
> Every chart must have a version number. A version must follow the [SemVer 2](https://semver.org/spec/v2.0.0.html) standard.

https://semver.org/
```
<version core> ::= <major> "." <minor> "." <patch>
```

2024-08-21 13:09 UTC, mosabua approved these changes
Lets roll with this.

2024-08-21 15:21 UTC, merged