Remove trailing slash in proxyTo and externalUrl in create and update backend methods
trinodb/trino-gateway pull request #570
Opened 2024-12-13 09:56 UTC by prakhar10

## Description
Remove trailing slash in proxyTo and externalUrl in create and update backend methods. Fixes https://github.com/trinodb/trino-gateway/issues/564

## Additional context and related issues

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(X) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

2024-12-14 11:58 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendProxyTo = backend.getProxyTo().replaceAll("/$", "");
Please add a helper method to remove trailing slash.

2024-12-14 11:58 UTC, ebyhr commented on gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java
> +        ProxyBackendConfiguration etl = new ProxyBackendConfiguration();
Please extract a test method.

2025-01-07 21:57 UTC, willmostly reviewed
Looks good % @ebyhr's comment

2025-01-07 21:57 UTC, willmostly commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendProxyTo = backend.getProxyTo().replaceAll("/$", "");
I think the same class should be fine

2025-01-14 18:52 UTC, prakhar10 commented
@willmostly @ebyhr can you please review.

2025-01-20 12:27 UTC, ebyhr commented on gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java
> +        etl.setExternalUrl("https://etl1.trino.gateway.io:443//");
Why do we want to remove more than one `/`?

2025-01-20 12:27 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        return url.replaceAll("/+$", "");
We should remove only one `/` in my opinion.

2025-01-20 14:14 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        return url.replaceAll("/+$", "");
Ok, I was thinking by chance if someone adds multiple slashes by mistake we should be able to handle that. Should I revert @ebyhr ?

2025-01-20 14:17 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        return url.replaceAll("/+$", "");
Yes.

2025-01-20 14:31 UTC, ebyhr commented
Please squash commits into one.

2025-01-20 16:39 UTC, prakhar10 commented
@ebyhr  can you check now please?

2025-01-20 22:24 UTC, ebyhr commented
> Revert handling multiple trailing slashes in url

Please remove the commit body.

2025-01-21 19:50 UTC, willmostly approved these changes

2025-01-22 00:20 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
These getters are called from other places. Please check all usages. For instance, The following place has the same issue because `UI_LOGIN_PATH` is `/ui/login`. 

https://github.com/trinodb/trino-gateway/blob/40337f6444362478beba6d555c1425f3490b3cc1/gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java#L132

2025-01-22 03:28 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
So the way I was thinking about this is to remove the slash while saving a new backend or updating a new backend so that later on any method that pulls this will always get the correct url from the database instead of trimming it in every part of the code.

2025-01-25 06:05 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
@ebyhr  any thoughts on this?

2025-01-28 22:16 UTC, mosabua commented
Is anything here still to be done besides a merge @willmostly @ebyhr ?

2025-01-29 02:42 UTC, ebyhr requested changes
(This PR isn't ready for merge)

2025-01-30 19:53 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
> So the way I was thinking about this is to remove the slash while saving a new backend or updating a new backend so that later on any method that pulls this will always get the correct url from the database instead of trimming it in every part of the code.

@ebyhr does this make sense?

2025-02-01 01:05 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
> while saving a new backend or updating a new backend

How does it work in existing environments?

2025-02-01 15:17 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
yeah I think if a cluster that is already added and has a trailing slash then that would still be an issue and they'll need to manually fix it. Ok I'll probably extract the helper method into a common Util class and then use it across other places in the codebase, does that sound ok @ebyhr ?

2025-02-10 21:31 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
Please can you review now.

2025-02-10 21:46 UTC, willmostly commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
> if a cluster that is already added and has a trailing slash then that would still be an issue and they'll need to manually fix it.

This  should be fine - clusters with URLs containing trailing slashes are unusable, so they should be very rare in existing environments

2025-02-10 21:50 UTC, prakhar10 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
> +        String backendExternalUrl = removeTrailingSlash(backend.getExternalUrl());
Should I revert the change from other files then?

2025-02-11 18:47 UTC, mosabua commented
@ebyhr @willmostly .. what are we doing here? Can we get this merged or are there still open concerns?

2025-03-04 19:30 UTC, merged

2025-03-04 20:19 UTC, willmostly commented
@mosabua suggested release note: 
```
* fix issue with backend URLs containing trailing slash (#564)
```