Add timeout handling for external routing group selector
trinodb/trino-gateway pull request #580
Opened 2024-12-31 05:27 UTC by Chaho12

## Description

Adds config options for users to change timeouts when making external routing requests.

## Additional context and related issues

- #579 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
* Add timeout handling for external routing group selector. ({issue}`issuenumber`)
```

2025-01-02 16:59 UTC, willmostly requested changes
This explicit configuration can be avoided by injecting the airlift HttpClient. See [ProxyRequestHandler](https://github.com/trinodb/trino-gateway/blob/a11e5a4967463fe054f2cee498c9cc88fc491903/gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java#L93) as an example. This approach will allow configuration of any supported HttpClient options and be consistent with the `proxy` and `monitor` configs

2025-01-09 10:39 UTC, Chaho12 commented
@willmostly @oneonestar PTAL. I added `Router` config that can be used to set Airlift HttpClient configs.

2025-01-09 19:00 UTC, willmostly requested changes
Looks good, just a couple minor comments from me

2025-01-10 00:23 UTC, Chaho12 commented on docs/routing-rules.md
> +the `serverConfig:` section with the `router` prefix.
I thought prefix is mandatory because I get this error. 
```
serverConfig:
    node.environment: test
    http-server.http.port: 8080
    http-server.process-forwarded: true
    log.levels-file: log.properties
    # https://trino.io/docs/current/admin/properties-logging.html
    log.max-size: 100MB
    log.max-total-size: 1GB
    log.compression: GZIP
    log.path: var/log/server.log
    http-client.request-timeout: 1s

...

2025-01-10T09:11:02.089+0900    ERROR   main    io.trino.gateway.ha.HaGatewayLauncher   Configuration is invalid
==========

Errors:

1) Configuration property 'http-client.request-timeout' was not used

==========

```

2025-01-21 14:57 UTC, willmostly commented on docs/routing-rules.md
> +the `serverConfig:` section with the `router` prefix.
Thanks, I guess this has changed since I last tested it

2025-01-21 14:59 UTC, willmostly approved these changes
LGTM!

2025-01-22 00:30 UTC, ebyhr commented on docs/routing-rules.md
> +  rules config file.
Please separate a commit for style changes.

2025-01-22 00:30 UTC, ebyhr commented on docs/routing-rules.md
> +Trino Gateway uses the Airlift HttpClient library when making HTTP requests.
Why do we want to mention the library and the class names?

2025-01-22 00:30 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java
> +            Request request = preparePost()
This change looks unrelated to "Support HttpClient options for external routing group selector". Please separate a commit.

2025-01-22 00:30 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ForRouter.java
> +}
```suggestion
public @interface ForRouter {}
```

2025-01-22 00:30 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingGroupSelector.java
> +            RequestAnalyzerConfig requestAnalyzerConfig, HttpClient httpClient)
Put all parametes on separate lines. 
```java
    static RoutingGroupSelector byRoutingExternal(
            RulesExternalConfiguration rulesExternalConfiguration,
            RequestAnalyzerConfig requestAnalyzerConfig,
            HttpClient httpClient)
    {
...
    }
```

2025-01-22 00:54 UTC, Chaho12 commented on docs/routing-rules.md
> +Trino Gateway uses the Airlift HttpClient library when making HTTP requests.
I thought it might not be obvious, so would be better off to tell them that you need to check Airlift conf, which is slightly different than other http clients

2025-01-22 01:10 UTC, Chaho12 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java
> +            Request request = preparePost()
Separted to https://github.com/trinodb/trino-gateway/pull/580/commits/fd379cd2184fc740c097b7ed268cb5207cb8d871 commit :) Thx for pointing it out ! Greatly appreciate it.

2025-01-22 01:16 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ForMonitor.java
> +public @interface ForMonitor{}
```suggestion
public @interface ForMonitor {}
```

2025-01-22 01:16 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ForRouter.java
> +public @interface ForRouter{}
```suggestion
public @interface ForRouter {}
```

2025-01-22 01:16 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/proxyserver/ForProxy.java
> +public @interface ForProxy{}
```suggestion
public @interface ForProxy {}
```

2025-01-22 01:16 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java
> +    ExternalRoutingGroupSelector(RulesExternalConfiguration rulesExternalConfiguration, RequestAnalyzerConfig requestAnalyzerConfig, HttpClient httpClient)
Move `httpClient` to the 1st argument.

2025-01-22 01:21 UTC, Chaho12 commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java
> +    ExternalRoutingGroupSelector(RulesExternalConfiguration rulesExternalConfiguration, RequestAnalyzerConfig requestAnalyzerConfig, HttpClient httpClient)
Sorry missed this!

2025-01-22 01:26 UTC, ebyhr commented on gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java
> +        this.httpClient = requireNonNull(httpClient, "httpClient is null");
I would move this line to the 1st line in this method for consistency with parameter's order.

2025-01-22 01:26 UTC, ebyhr commented on docs/routing-rules.md
> +Please refer to the [Trino HTTP Client properties](
Client -> client

2025-01-22 01:26 UTC, ebyhr commented on docs/routing-rules.md
> +Trino Gateway uses the Airlift HttpClient library when making HTTP requests.
There is no need to mention such names because they are not important in my opinion. Just linking to https://trino.io/docs/current/admin/properties-http-client.html looks sufficient.

2025-01-22 05:00 UTC, Chaho12 commented on docs/routing-rules.md
> +Trino Gateway uses the Airlift HttpClient library when making HTTP requests.
Sounds fair enough :)

2025-01-22 20:32 UTC, ebyhr commented on docs/routing-rules.md
> +### Configuring API Requests with HttpClient Config
```suggestion
### Configuring API requests with HTTP client config
```

2025-01-22 20:32 UTC, ebyhr commented on docs/routing-rules.md
> +You can configure the HttpClient by adding the following configuration to
```suggestion
You can configure the HTTP client by adding the following configuration to
```

2025-01-23 00:58 UTC, ebyhr approved these changes

2025-01-23 00:58 UTC, merged