Fixes a wrong logging format in QueryIdCachingProxyHandler
trinodb/trino-gateway pull request #93
Opened 2023-11-16 14:00 UTC by Barbayar

### Context
A small fix for a logging format in `QueryIdCachingProxyHandler`.

2023-11-17 05:18 UTC, Chaho12 requested changes
I think you missed CLA.
I noticed same issue and was planning to fix with leaving
`log.info("Requested query details: {}", queryDetail);` code too. What do you think?

2023-11-21 17:20 UTC, mosabua commented
@Barbayar please submit a CLA

2023-11-21 17:53 UTC, Barbayar commented
Sorry for a delayed response. Just signed and submitted.

2023-11-21 18:04 UTC, mosabua commented
No worries @Barbayar .. it will probably take a bit until we get to process it.

2023-11-21 18:10 UTC, Barbayar commented
@Chaho12 I'm not sure if dumping the whole object is a good idea. It already contains the [user](https://github.com/trinodb/trino-gateway/blob/6b1047b116fd9fe3f3398b13c23c2f4e847cc6ca/gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryHistoryManager.java#L20) information. Also, we don't know who is going to add a sensitive data into [QueryHistoryManager.QueryDetail](https://github.com/trinodb/trino-gateway/blob/6b1047b116fd9fe3f3398b13c23c2f4e847cc6ca/gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryHistoryManager.java#L17C9-L17C20) in the future.

2023-12-07 17:52 UTC, mosabua commented
@cla-bot check

2023-12-07 17:53 UTC, mosabua commented
I agree that we dont want to leak the full query details into the log.

2023-12-07 17:53 UTC, mosabua approved these changes

2023-12-07 17:53 UTC, merged